[package]
edition = "2021"
name = "runtime"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = "3.1.5"
# subxt = {path = "../../subxt/subxt"}
subxt = {version = "0.22.0"}

[dev-dependencies]
